### ISSUE TITLE
Checklist for 0.9 release

### ISSUE THREAD

**Issue by mconlon17** [mconlon17/vivo-pump#102]
* [ ] All generic examples complete
* [ ] All UF examples complete
* [ ] All wiki pages complete
* [ ] All enhancements marked for 0.9 complete
* [x] All unit tests pass

**Comment by mconlon17** [comment]
Dumb idea.  Just work the issues in the milestone.  No need for checklist.
